# Generated by Django 4.0.6 on 2022-07-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.TextField(max_length=30)),
                ('article_date', models.DateField()),
                ('article_text', models.CharField(max_length=500)),
                ('article_img', models.ImageField(upload_to='', verbose_name='blog_images/')),
            ],
        ),
    ]
